### ISSUE TITLE
Error after clicking truncate from FLImBrush Alpha v0.1.0 

### ISSUE THREAD

**Issue by RALSchoop** [marculab/FLImBrushDataProcessingTool#3]
I tried using the latest release version of the FLImBrush software to deconvolve some of the more recent standards data from UC Davis entitled: Standards_AlexData. From this data I've tried processing different data files, however I got an error when trying to process them. In particular when processing 'POPOP\POP_10uM\240823_GBSF_FB_LoS_15.tdms' I was met with the following error message after pressing the truncate button:
![Screenshot 2024-10-08 093931_FLImBrush_Error_Matlab_At_Truncation](https://github.com/user-attachments/assets/9f0d134a-f37e-4f67-ab5e-1964c752bbea)

I used the APD files located in the release under 'APDDetectorFile/UCD_GBSF/'.

What could be the cause of this error and what could be a possible fix? Are there any further details I should provide regarding this issue?

**Comment by xnzhou1991** [comment]
Hi Ryan, one of your channels has no data. The software trys to find a waveform peak and truncate the data. If there is no data but only noise, the 'peak' could be anywhere. If it is too close to the tail of the data, you run out of data to truncate. 

I will implement a check to make sure this is addressed for next release.
